### ISSUE TITLE
Integrate with Google analytics

### ISSUE THREAD

**Issue by filfreire** [yegor256/elegantobjects.github.io#2]
- activate google analytics for `elegantobjects.github.io`
- Add script part at the end to measure page visits (you can do it like this: https://github.com/filfreire/filfreire.github.io/commit/1f762991e20bed75e6bc359d8f999747018258f5 )

@yegor256 FYI

**Comment by 0crat** [comment]
@filfreire I'm not managing this repo, remove the [webhook](https://github.com/yegor256/elegantobjects.github.io/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@filfreire right, thanks, fixed.

**Comment by 0crat** [comment]
I'm not managing ` yegor256/elegantobjects.github.io ` GitHub repository. You have to contact me in Slack first. Our [policy](http://datum.zerocracy.com/pages/policy.html) explains how.
