### ISSUE TITLE
Label EO projects

### ISSUE THREAD

**Issue by t-izbassar** [yegor256/elegantobjects.github.io#27]
I think we could create some fancy label for github projects, marking that project is made having eo principles in mind.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@t-izbassar I like the idea, thanks!

**Comment by yegor256** [comment]
@t-izbassar what do you think? https://cdn.rawgit.com/yegor256/elegantobjects.github.io/831bc49a/badge.svg

**Comment by t-izbassar** [comment]
@yegor256 nice one)

**Comment by yegor256** [comment]
@t-izbassar I put this badge to all my GitHub repos. Thanks for the idea.
