### ISSUE TITLE
StackOverflow tag

### ISSUE THREAD

**Issue by ashtonhogan** [yegor256/elegantobjects.github.io#28]
There is no elegantobjects tag on StackOverflow and I do not have enough reputation to create it

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ashtonhogan they won't let us do that, since it's not related to any technology. We should use `oop` or `cactoos` (if it's product related).

**Comment by ashtonhogan** [comment]
@yegor256 I've changed my mind. I think it's better to just ask questions directly on github. As long as you have similar regulations to SO, you should be able to achieve similar quality for SEO purposes and user readability

**Comment by merobero** [comment]
https://github.com/yegor256/elegantobjects.github.io/issues/3#issuecomment-470848926

**Comment by merobero** [comment]
https://github.com/yegor256/elegantobjects.github.io/issues/3#issuecomment-470848926

**Comment by merobero** [comment]
https://github.com/yegor256/elegantobjects.github.io/issues/3#issuecomment-470848926
