### ISSUE TITLE
delete this repo?

### ISSUE THREAD

**Issue by ashtonhogan** [yegor256/elegantobjects.github.io#29]
elegantobjects.org is wrong actually. It only talks about "design principles" but that's not what this is really about. This is more like a set of principles...

Support principles, design principles, license principles, "asking questions" principles, "raising bugs" principles, contribution principles. We need something like: elegantsoftware.org

As a consumer, I don't want to manually search through millions of repositories, trying to find good quality projects. I just want projects that use the "elegant standard" which is all these principles...

As a producer, I don't want to wing it, I wanna know and be guided on the best principles so that I can just focus on code and not worry about all that other stuff and if I'm doing it properly or not

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ashtonhogan elegant objects is __only__ about object-oriented programming. What you are talking about has nothing to do with OOP. You should check XDSD.org or Zerocracy.com, they are about management.
