### ISSUE TITLE
Make yegor256 manager of repository

### ISSUE THREAD

**Issue by filfreire** [yegor256/elegantobjects.github.io#3]
Fix issue that appears:

```
@filfreire I'm not managing this repo, remove the webhook or contact me in Slack //cc @yegor256
```
@yegor256 FYI

**Comment by 0crat** [comment]
@filfreire I'm not managing this repo, remove the [webhook](https://github.com/yegor256/elegantobjects.github.io/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@filfreire fixed, thanks

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/elegantobjects.github.io#3` is not assigned, can't get start time

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/elegantobjects.github.io#3` was not in scope

**Comment by merobero** [comment]
My dear friend yegor256

I took you from man to man. Why did you put my email in the ban from selling or paying Zold .. I took my money I work with Max in Sharm El Sheikh and he gave me Zold for services between us .. Now I did not get my money .. Why did you block my money from Man for man .. You would be the group manager and not a thief .. Please pay my money 140 dollars in my wallet. Please, Director

**Comment by merobero** [comment]
My dear friend yegor256

I took you from man to man. Why did you put my email in the ban from selling or paying Zold .. I took my money I work with Max in Sharm El Sheikh and he gave me Zold for services between us .. Now I did not get my money .. Why did you block my money from Man for man .. You would be the group manager and not a thief .. Please pay my money 140 dollars in my wallet. Please, Director
