### ISSUE TITLE
donate button

### ISSUE THREAD

**Issue by ashtonhogan** [yegor256/elegantobjects.github.io#30]
add a donate button to the page, i.e. [donate](https://www.coinpayments.net/index.php?cmd=_donate&reset=1&merchant=91248a0993242d7bb62ccec107a3e610&currency=BTC&amountf=0.001&item_name=Donation%20to%20Ashton%20Hogan%20Limited)

The above example requires a coinpayments.net account but if you don't want one there are plenty of other options

I don't see many other ways to monetize this work apart from donate...

alternatively if there's a patreon?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by ashtonhogan** [comment]
@yegor256 bump

**Comment by yegor256** [comment]
@ashtonhogan what is the point? What do we need money for?

**Comment by ashtonhogan** [comment]
@yegor256 I'm going off the assumption that everything you do should be monetized but if this is all purely promotional or hobby then feel free to close this issue

**Comment by yegor256** [comment]
@ashtonhogan yes, maybe in the future, when we will be ready to provide something for the money we collect. In the mean time, if you (or someone else) wants to donate, just buy my books)
