### ISSUE TITLE
Shields style badge with logo

### ISSUE THREAD

**Issue by ashtonhogan** [yegor256/elegantobjects.github.io#31]
@yegor256 Can't you just standardise it so it looks like all the other default [shields](https://shields.io/)?

This could look better:

[<img src="http://www.elegantobjects.org/badge.svg">](http://www.elegantobjects.org/#principles)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by ashtonhogan** [comment]
Will submit sample once this PR is merged: https://github.com/badges/shields/pull/1552

**Comment by ashtonhogan** [comment]
shields does not permit anyone to upload their logos so you have to do it yourself. I've uploaded the badges and icons here: https://github.com/yegor256/elegantobjects.github.io/pull/33

Previews:

<img src="https://raw.githubusercontent.com/ashtonhogan/elegantobjects.github.io/d62fa3f7e6133e1d780c11cc8144183bb8ececae/badge-1.svg" />

<img src="https://raw.githubusercontent.com/ashtonhogan/elegantobjects.github.io/d62fa3f7e6133e1d780c11cc8144183bb8ececae/badge-2.svg" />
